name: dcubo_iconify_uil
description: Iconify icons for Unicons.
version: 4.2.0
lastModified: 1734422330
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0