name: dcubo_iconify_unjs
description: Iconify icons for UnJS Logos.
version: 0.2.0
lastModified: 1721244277
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0