name: dcubo_iconify_lucide
description: Iconify icons for Lucide.
version: 0.2.0
lastModified: 1740899925
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0