name: dcubo_iconify_subway
description: Iconify icons for Subway Icon Set.
version: 0.3.0
lastModified: 1717394043
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0