name: dcubo_iconify
description: Main package needed to use all other Iconify icons in your project
version: 0.1.1
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4