name: dcubo_iconify_mynaui
description: Iconify icons for Myna UI Icons.
version: 0.2.0
lastModified: 1732517700
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0