name: dcubo_iconify_entypo
description: Iconify icons for Entypo+.
version: 0.3.0
lastModified: 1722793304
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0