name: dcubo_iconify_meteor_icons
description: Iconify icons for Meteor Icons.
version: 0.3.0
lastModified: 1731135235
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0