name: dcubo_iconify_file_icons
description: Iconify icons for File Icons.
version: 0.4.0
lastModified: 1721244157
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0