name: dcubo_iconify_foundation
description: Iconify icons for Foundation.
version: 3.0.0
lastModified: 1722793848
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0