name: dcubo_iconify_fontelico
description: Iconify icons for Fontelico.
version: 0.2.0
lastModified: 1722793826
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0