name: dcubo_iconify_bitcoin_icons
description: Iconify icons for Bitcoin Icons.
version: 0.1.10
lastModified: 1722792992
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0