name: dcubo_iconify_charm
description: Iconify icons for Charm Icons.
version: 0.12.1
lastModified: 1722793079
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0