name: "dcubo_iconify_workspace"
publish_to: "none"
repository: "https://github.com/rmortes/dcubo-iconify/"
issue_tracker: "https://github.com/rmortes/dcubo-iconify/issues"
environment:
  sdk: ">=3.6.0 <4.0.0"
dev_dependencies:
  melos: "^6.3.2"
  very_good_analysis: "^6.0.0"
workspace:
  - "packages/dcubo_iconify_devicon_original"
  - "packages/dcubo_iconify_circle_flags"
  - "packages/dcubo_iconify_cryptocurrency_color"
  - "packages/dcubo_iconify_ei"
  - "packages/dcubo_iconify_cryptocurrency"
  - "packages/dcubo_iconify_devicon_line"
  - "packages/dcubo_iconify_bubbles"
  - "packages/dcubo_iconify_bitcoin_icons"
  - "packages/dcubo_iconify_academicons"
  - "packages/dcubo_iconify_devicon_plain"
  - "packages/dcubo_iconify_codicon"
  - "packages/dcubo_iconify_devicon"
  - "packages/dcubo_iconify_bxl"
  - "packages/dcubo_iconify_codex"
  - "packages/dcubo_iconify_cif"
  - "packages/dcubo_iconify_bi"
  - "packages/dcubo_iconify_basil"
  - "packages/dcubo_iconify_aws"
  - "packages/dcubo_iconify_brandico"
  - "packages/dcubo_iconify_catppuccin"
  - "packages/dcubo_iconify_duo_icons"
  - "packages/dcubo_iconify_circum"
  - "packages/dcubo_iconify_el"
  - "packages/dcubo_iconify_ci"
  - "packages/dcubo_iconify_clarity"
  - "packages/dcubo_iconify_cbi"
  - "packages/dcubo_iconify_cuida"
  - "packages/dcubo_iconify_bxs"
  - "packages/dcubo_iconify_akar_icons"
  - "packages/dcubo_iconify_charm"
  - "packages/dcubo_iconify_cil"
  - "packages/dcubo_iconify"
  - "packages/dcubo_iconify_cib"
  - "packages/dcubo_iconify_carbon"
  - "packages/dcubo_iconify_arcticons"
  - "packages/dcubo_iconify_dashicons"
  - "packages/dcubo_iconify_ant_design"
  - "packages/dcubo_iconify_bpmn"
  - "packages/dcubo_iconify_covid"
  - "packages/dcubo_iconify_bx"
  - "packages/dcubo_iconify_bytesize"
scripts:
  analyze:
    exec: "dart analyze ."
