name: "dcubo_iconify_workspace"
publish_to: "none"
repository: "https://github.com/rmortes/dcubo-iconify/"
issue_tracker: "https://github.com/rmortes/dcubo-iconify/issues"
environment:
  sdk: ">=3.6.0 <4.0.0"
dev_dependencies:
  melos: "^6.3.2"
  very_good_analysis: "^6.0.0"
workspace:
  - "packages/dcubo_iconify_fa6_solid"
  - "packages/dcubo_iconify_devicon_original"
  - "packages/dcubo_iconify_circle_flags"
  - "packages/dcubo_iconify_fa"
  - "packages/dcubo_iconify_cryptocurrency_color"
  - "packages/dcubo_iconify_ei"
  - "packages/dcubo_iconify_flat_color_icons"
  - "packages/dcubo_iconify_flat_ui"
  - "packages/dcubo_iconify_famicons"
  - "packages/dcubo_iconify_cryptocurrency"
  - "packages/dcubo_iconify_devicon_line"
  - "packages/dcubo_iconify_et"
  - "packages/dcubo_iconify_f7"
  - "packages/dcubo_iconify_bubbles"
  - "packages/dcubo_iconify_fluent_mdl2"
  - "packages/dcubo_iconify_bitcoin_icons"
  - "packages/dcubo_iconify_academicons"
  - "packages/dcubo_iconify_devicon_plain"
  - "packages/dcubo_iconify_codicon"
  - "packages/dcubo_iconify_fa6_brands"
  - "packages/dcubo_iconify_devicon"
  - "packages/dcubo_iconify_bxl"
  - "packages/dcubo_iconify_flowbite"
  - "packages/dcubo_iconify_codex"
  - "packages/dcubo_iconify_fa_solid"
  - "packages/dcubo_iconify_flag"
  - "packages/dcubo_iconify_emojione"
  - "packages/dcubo_iconify_cif"
  - "packages/dcubo_iconify_bi"
  - "packages/dcubo_iconify_basil"
  - "packages/dcubo_iconify_aws"
  - "packages/dcubo_iconify_fluent_emoji_high_contrast"
  - "packages/dcubo_iconify_fe"
  - "packages/dcubo_iconify_brandico"
  - "packages/dcubo_iconify_catppuccin"
  - "packages/dcubo_iconify_duo_icons"
  - "packages/dcubo_iconify_entypo"
  - "packages/dcubo_iconify_fluent_color"
  - "packages/dcubo_iconify_circum"
  - "packages/dcubo_iconify_el"
  - "packages/dcubo_iconify_eva"
  - "packages/dcubo_iconify_ci"
  - "packages/dcubo_iconify_ep"
  - "packages/dcubo_iconify_fluent_emoji_flat"
  - "packages/dcubo_iconify_clarity"
  - "packages/dcubo_iconify_file_icons"
  - "packages/dcubo_iconify_fa6_regular"
  - "packages/dcubo_iconify_fa_regular"
  - "packages/dcubo_iconify_cbi"
  - "packages/dcubo_iconify_cuida"
  - "packages/dcubo_iconify_fluent_emoji"
  - "packages/dcubo_iconify_bxs"
  - "packages/dcubo_iconify_emojione_monotone"
  - "packages/dcubo_iconify_akar_icons"
  - "packages/dcubo_iconify_charm"
  - "packages/dcubo_iconify_feather"
  - "packages/dcubo_iconify_flagpack"
  - "packages/dcubo_iconify_fluent"
  - "packages/dcubo_iconify_cil"
  - "packages/dcubo_iconify"
  - "packages/dcubo_iconify_cib"
  - "packages/dcubo_iconify_carbon"
  - "packages/dcubo_iconify_arcticons"
  - "packages/dcubo_iconify_dashicons"
  - "packages/dcubo_iconify_ant_design"
  - "packages/dcubo_iconify_bpmn"
  - "packages/dcubo_iconify_entypo_social"
  - "packages/dcubo_iconify_covid"
  - "packages/dcubo_iconify_bx"
  - "packages/dcubo_iconify_eos_icons"
  - "packages/dcubo_iconify_fa_brands"
  - "packages/dcubo_iconify_fad"
  - "packages/dcubo_iconify_bytesize"
  - "packages/dcubo_iconify_emojione_v1"
scripts:
  analyze:
    exec: "dart analyze ."
