name: "dcubo_iconify_workspace"
publish_to: "none"
repository: "https://github.com/rmortes/dcubo-iconify/"
issue_tracker: "https://github.com/rmortes/dcubo-iconify/issues"
environment:
  sdk: ">=3.6.0 <4.0.0"
dev_dependencies:
  melos: "^6.3.2"
  very_good_analysis: ^7.0.0
workspace:
  - "packages/dcubo_iconify_raphael"
  - "packages/dcubo_iconify_fa6_solid"
  - "packages/dcubo_iconify_gridicons"
  - "packages/dcubo_iconify_oi"
  - "packages/dcubo_iconify_iwwa"
  - "packages/dcubo_iconify_zmdi"
  - "packages/dcubo_iconify_devicon_original"
  - "packages/dcubo_iconify_la"
  - "packages/dcubo_iconify_circle_flags"
  - "packages/dcubo_iconify_fa"
  - "packages/dcubo_iconify_token"
  - "packages/dcubo_iconify_ls"
  - "packages/dcubo_iconify_cryptocurrency_color"
  - "packages/dcubo_iconify_icon_park_twotone"
  - "packages/dcubo_iconify_ei"
  - "packages/dcubo_iconify_nimbus"
  - "packages/dcubo_iconify_pepicons_print"
  - "packages/dcubo_iconify_solar"
  - "packages/dcubo_iconify_il"
  - "packages/dcubo_iconify_whh"
  - "packages/dcubo_iconify_weui"
  - "packages/dcubo_iconify_flat_color_icons"
  - "packages/dcubo_iconify_flat_ui"
  - "packages/dcubo_iconify_famicons"
  - "packages/dcubo_iconify_cryptocurrency"
  - "packages/dcubo_iconify_devicon_line"
  - "packages/dcubo_iconify_ix"
  - "packages/dcubo_iconify_et"
  - "packages/dcubo_iconify_f7"
  - "packages/dcubo_iconify_ooui"
  - "packages/dcubo_iconify_game_icons"
  - "packages/dcubo_iconify_bubbles"
  - "packages/dcubo_iconify_fluent_mdl2"
  - "packages/dcubo_iconify_ic"
  - "packages/dcubo_iconify_bitcoin_icons"
  - "packages/dcubo_iconify_wpf"
  - "packages/dcubo_iconify_lsicon"
  - "packages/dcubo_iconify_pepicons_pencil"
  - "packages/dcubo_iconify_svg_spinners"
  - "packages/dcubo_iconify_academicons"
  - "packages/dcubo_iconify_devicon_plain"
  - "packages/dcubo_iconify_proicons"
  - "packages/dcubo_iconify_lucide"
  - "packages/dcubo_iconify_pajamas"
  - "packages/dcubo_iconify_streamline"
  - "packages/dcubo_iconify_map"
  - "packages/dcubo_iconify_mdi_light"
  - "packages/dcubo_iconify_wi"
  - "packages/dcubo_iconify_grommet_icons"
  - "packages/dcubo_iconify_codicon"
  - "packages/dcubo_iconify_fa6_brands"
  - "packages/dcubo_iconify_devicon"
  - "packages/dcubo_iconify_bxl"
  - "packages/dcubo_iconify_mdi"
  - "packages/dcubo_iconify_gala"
  - "packages/dcubo_iconify_ph"
  - "packages/dcubo_iconify_marketeq"
  - "packages/dcubo_iconify_flowbite"
  - "packages/dcubo_iconify_si"
  - "packages/dcubo_iconify_ps"
  - "packages/dcubo_iconify_formkit"
  - "packages/dcubo_iconify_unjs"
  - "packages/dcubo_iconify_websymbol"
  - "packages/dcubo_iconify_gis"
  - "packages/dcubo_iconify_codex"
  - "packages/dcubo_iconify_lucide_lab"
  - "packages/dcubo_iconify_token_branded"
  - "packages/dcubo_iconify_fa_solid"
  - "packages/dcubo_iconify_flag"
  - "packages/dcubo_iconify_emojione"
  - "packages/dcubo_iconify_cif"
  - "packages/dcubo_iconify_heroicons_outline"
  - "packages/dcubo_iconify_topcoat"
  - "packages/dcubo_iconify_icomoon_free"
  - "packages/dcubo_iconify_icons8"
  - "packages/dcubo_iconify_heroicons"
  - "packages/dcubo_iconify_iconamoon"
  - "packages/dcubo_iconify_jam"
  - "packages/dcubo_iconify_mynaui"
  - "packages/dcubo_iconify_pixelarticons"
  - "packages/dcubo_iconify_uit"
  - "packages/dcubo_iconify_uis"
  - "packages/dcubo_iconify_subway"
  - "packages/dcubo_iconify_nonicons"
  - "packages/dcubo_iconify_logos"
  - "packages/dcubo_iconify_bi"
  - "packages/dcubo_iconify_maki"
  - "packages/dcubo_iconify_mage"
  - "packages/dcubo_iconify_fontelico"
  - "packages/dcubo_iconify_fontisto"
  - "packages/dcubo_iconify_basil"
  - "packages/dcubo_iconify_aws"
  - "packages/dcubo_iconify_material_symbols"
  - "packages/dcubo_iconify_radix_icons"
  - "packages/dcubo_iconify_fluent_emoji_high_contrast"
  - "packages/dcubo_iconify_fe"
  - "packages/dcubo_iconify_tdesign"
  - "packages/dcubo_iconify_brandico"
  - "packages/dcubo_iconify_qlementine_icons"
  - "packages/dcubo_iconify_catppuccin"
  - "packages/dcubo_iconify_duo_icons"
  - "packages/dcubo_iconify_entypo"
  - "packages/dcubo_iconify_fluent_color"
  - "packages/dcubo_iconify_circum"
  - "packages/dcubo_iconify_simple_line_icons"
  - "packages/dcubo_iconify_el"
  - "packages/dcubo_iconify_stash"
  - "packages/dcubo_iconify_pepicons"
  - "packages/dcubo_iconify_oui"
  - "packages/dcubo_iconify_fxemoji"
  - "packages/dcubo_iconify_line_md"
  - "packages/dcubo_iconify_lineicons"
  - "packages/dcubo_iconify_eva"
  - "packages/dcubo_iconify_majesticons"
  - "packages/dcubo_iconify_ci"
  - "packages/dcubo_iconify_ep"
  - "packages/dcubo_iconify_tabler"
  - "packages/dcubo_iconify_humbleicons"
  - "packages/dcubo_iconify_fluent_emoji_flat"
  - "packages/dcubo_iconify_typcn"
  - "packages/dcubo_iconify_clarity"
  - "packages/dcubo_iconify_file_icons"
  - "packages/dcubo_iconify_openmoji"
  - "packages/dcubo_iconify_hugeicons"
  - "packages/dcubo_iconify_fa6_regular"
  - "packages/dcubo_iconify_guidance"
  - "packages/dcubo_iconify_nrk"
  - "packages/dcubo_iconify_icon_park_outline"
  - "packages/dcubo_iconify_vaadin"
  - "packages/dcubo_iconify_zondicons"
  - "packages/dcubo_iconify_fa_regular"
  - "packages/dcubo_iconify_vscode_icons"
  - "packages/dcubo_iconify_skill_icons"
  - "packages/dcubo_iconify_system_uicons"
  - "packages/dcubo_iconify_cbi"
  - "packages/dcubo_iconify_meteor_icons"
  - "packages/dcubo_iconify_memory"
  - "packages/dcubo_iconify_ri"
  - "packages/dcubo_iconify_gravity_ui"
  - "packages/dcubo_iconify_cuida"
  - "packages/dcubo_iconify_fluent_emoji"
  - "packages/dcubo_iconify_rivet_icons"
  - "packages/dcubo_iconify_medical_icon"
  - "packages/dcubo_iconify_bxs"
  - "packages/dcubo_iconify_emojione_monotone"
  - "packages/dcubo_iconify_heroicons_solid"
  - "packages/dcubo_iconify_teenyicons"
  - "packages/dcubo_iconify_streamline_emojis"
  - "packages/dcubo_iconify_akar_icons"
  - "packages/dcubo_iconify_material_symbols_light"
  - "packages/dcubo_iconify_charm"
  - "packages/dcubo_iconify_noto"
  - "packages/dcubo_iconify_feather"
  - "packages/dcubo_iconify_flagpack"
  - "packages/dcubo_iconify_fluent"
  - "packages/dcubo_iconify_cil"
  - "packages/dcubo_iconify"
  - "packages/dcubo_iconify_iconoir"
  - "packages/dcubo_iconify_cib"
  - "packages/dcubo_iconify_carbon"
  - "packages/dcubo_iconify_arcticons"
  - "packages/dcubo_iconify_dashicons"
  - "packages/dcubo_iconify_si_glyph"
  - "packages/dcubo_iconify_garden"
  - "packages/dcubo_iconify_meteocons"
  - "packages/dcubo_iconify_ant_design"
  - "packages/dcubo_iconify_ion"
  - "packages/dcubo_iconify_vs"
  - "packages/dcubo_iconify_noto_v1"
  - "packages/dcubo_iconify_geo"
  - "packages/dcubo_iconify_prime"
  - "packages/dcubo_iconify_icon_park"
  - "packages/dcubo_iconify_bpmn"
  - "packages/dcubo_iconify_pepicons_pop"
  - "packages/dcubo_iconify_simple_icons"
  - "packages/dcubo_iconify_icon_park_solid"
  - "packages/dcubo_iconify_entypo_social"
  - "packages/dcubo_iconify_healthicons"
  - "packages/dcubo_iconify_uil"
  - "packages/dcubo_iconify_mi"
  - "packages/dcubo_iconify_covid"
  - "packages/dcubo_iconify_twemoji"
  - "packages/dcubo_iconify_quill"
  - "packages/dcubo_iconify_bx"
  - "packages/dcubo_iconify_gg"
  - "packages/dcubo_iconify_uiw"
  - "packages/dcubo_iconify_uim"
  - "packages/dcubo_iconify_foundation"
  - "packages/dcubo_iconify_mono_icons"
  - "packages/dcubo_iconify_eos_icons"
  - "packages/dcubo_iconify_fa_brands"
  - "packages/dcubo_iconify_fad"
  - "packages/dcubo_iconify_octicon"
  - "packages/dcubo_iconify_bytesize"
  - "packages/dcubo_iconify_lets_icons"
  - "packages/dcubo_iconify_emojione_v1"
  - "packages/dcubo_iconify_mingcute"
scripts:
  analyze:
    exec: "dart analyze ."
