name: dcubo_iconify_cil
description: Iconify icons for CoreUI Free.
version: 2.0.1
lastModified: 1721920996
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0