name: dcubo_iconify_rivet_icons
description: Iconify icons for Rivet Icons.
version: 0.1.0
lastModified: 1718879852
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0