name: dcubo_iconify_maki
description: Iconify icons for Maki.
version: 8.2.0
lastModified: 1740637615
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0