name: dcubo_iconify_basil
description: Iconify icons for Basil.
version: 0.3.0
lastModified: 1722792979
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0