name: dcubo_iconify_iconoir
description: Iconify icons for Iconoir.
version: 7.10.1
lastModified: 1735410179
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0