name: dcubo_iconify_uit
description: Iconify icons for Unicons Thin Line.
version: 4.2.0
lastModified: 1734422346
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0