name: dcubo_iconify_devicon
description: Iconify icons for Devicon.
version: 0.2.0
lastModified: 1740377666
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0