name: dcubo_iconify_mi
description: Iconify icons for Mono Icons.
version: 1.3.1
lastModified: 1722795192
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0