name: dcubo_iconify_ci
description: Iconify icons for coolicons.
version: 0.1.0
lastModified: 1722793086
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0