name: dcubo_iconify_gridicons
description: Iconify icons for Gridicons.
version: 3.4.2
lastModified: 1722793920
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0