name: dcubo_iconify_fa_solid
description: Iconify icons for Font Awesome 5 Solid.
version: 5.15.4
lastModified: 1722793361
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0