name: dcubo_iconify_majesticons
description: Iconify icons for Majesticons.
version: 2.1.2
lastModified: 1722794692
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0