name: dcubo_iconify_material_symbols
description: Iconify icons for Material Symbols.
version: 0.3.0
lastModified: 1738223466
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0