name: dcubo_iconify_il
description: Iconify icons for Icalicons.
version: 0.0.1
lastModified: 1702312720
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0