name: dcubo_iconify_circle_flags
description: Iconify icons for Circle Flags.
version: 1.0.0
lastModified: 1738222716
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0