name: dcubo_iconify_bi
description: Iconify icons for Bootstrap Icons.
version: 1.11.3
lastModified: 1704439122
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0