name: dcubo_iconify_oi
description: Iconify icons for Open Iconic.
version: 1.1.1
lastModified: 1722795342
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0