name: dcubo_iconify_grommet_icons
description: Iconify icons for Grommet Icons.
version: 4.12.1
lastModified: 1716788279
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0