name: dcubo_iconify_emojione
description: Iconify icons for Emoji One (Colored).
version: 2.3.0
lastModified: 1722793290
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0