name: dcubo_iconify_fluent_color
description: Iconify icons for Fluent UI System Color Icons.
version: 1.1.273
lastModified: 1740899804
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0