name: dcubo_iconify_fa_brands
description: Iconify icons for Font Awesome 5 Brands.
version: 5.15.4
lastModified: 1722793346
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0