name: dcubo_iconify_openmoji
description: Iconify icons for OpenMoji.
version: 0.2.0
lastModified: 1740900182
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0