name: dcubo_iconify_lets_icons
description: Iconify icons for Lets Icons.
version: 0.3.0
lastModified: 1722794599
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0