name: dcubo_iconify_uiw
description: Iconify icons for uiw icons.
version: 2.6.10
lastModified: 1719211757
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0