name: dcubo_iconify_websymbol
description: Iconify icons for Web Symbols Liga.
version: 0.3.0
lastModified: 1702314241
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0