name: dcubo_iconify_f7
description: Iconify icons for Framework7 Icons.
version: 5.0.5
lastModified: 1722793337
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0