name: dcubo_iconify_flag
description: Iconify icons for Flag Icons.
version: 7.3.2
lastModified: 1737129798
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0