name: dcubo_iconify_healthicons
description: Iconify icons for Health Icons.
version: 2.0.0
lastModified: 1740637582
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0