name: dcubo_iconify_uim
description: Iconify icons for Unicons Monochrome.
version: 4.2.0
lastModified: 1734422334
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0