name: dcubo_iconify_flat_ui
description: Iconify icons for Flat UI Icons.
version: 0.1.0
lastModified: 1722793447
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0