name: dcubo_iconify_fxemoji
description: Iconify icons for Firefox OS Emoji.
version: 0.0.2
lastModified: 1722793859
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0