name: dcubo_iconify_flat_color_icons
description: Iconify icons for Flat Color Icons.
version: 1.0.2
lastModified: 1722793442
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0