name: dcubo_iconify_icons8
description: Iconify icons for Icons8 Windows 10 Icons.
version: 1.0.0
lastModified: 1722794108
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0