name: dcubo_iconify_ph
description: Iconify icons for Phosphor.
version: 2.1.1
lastModified: 1714973607
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0