name: dcubo_iconify_fluent_emoji_high_contrast
description: Iconify icons for Fluent Emoji High Contrast.
version: 0.3.0
lastModified: 1738483670
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0