name: dcubo_iconify_lsicon
description: Iconify icons for Lsicon.
version: 0.1.0
lastModified: 1727941155
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0