name: dcubo_iconify_logos
description: Iconify icons for SVG Logos.
version: 0.1.0
lastModified: 1727941370
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0