name: dcubo_iconify_nonicons
description: Iconify icons for Nonicons.
version: 0.0.18
lastModified: 1734334346
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0