name: dcubo_iconify_fluent_emoji
description: Iconify icons for Fluent Emoji.
version: 0.1.0
lastModified: 1738483936
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0