name: dcubo_iconify_guidance
description: Iconify icons for Guidance.
version: 0.2.0
lastModified: 1722793934
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0