name: dcubo_iconify_eos_icons
description: Iconify icons for EOS Icons.
version: 5.4.0
lastModified: 1722793311
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0