name: dcubo_iconify_ls
description: Iconify icons for Ligature Symbols.
version: 0.3.0
lastModified: 1722794659
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0