name: dcubo_iconify_solar
description: Iconify icons for Solar.
version: 0.2.0
lastModified: 1722795734
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0