name: dcubo_iconify_flagpack
description: Iconify icons for Flagpack.
version: 2.0.0
lastModified: 1722793438
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0