name: dcubo_iconify_fa6_brands
description: Iconify icons for Font Awesome Brands.
version: 6.7.2
lastModified: 1734421834
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0