name: dcubo_iconify_gis
description: Iconify icons for Font-GIS.
version: 1.0.6
lastModified: 1736838985
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0