name: dcubo_iconify_si
description: Iconify icons for Sargam Icons.
version: 0.2.0
lastModified: 1728378345
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0