name: dcubo_iconify_bytesize
description: Iconify icons for Bytesize Icons.
version: 1.4.0
lastModified: 1722793032
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0