name: dcubo_iconify_formkit
description: Iconify icons for FormKit Icons.
version: 0.2.0
lastModified: 1712643767
repository: https://github.com/rmortes/dcubo-iconify/
issue_tracker: https://github.com/rmortes/dcubo-iconify/issues
resolution: workspace

environment:
  sdk: ^3.6.0